//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOfWorkmans
    {
        public int Id { get; set; }
        public int WorkmanId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Workman Workman { get; set; }
    }
}
